/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#000000",
        "on-secondary-fixed": "#000000",
        "surface-tint": "#f97316",
        "on-secondary": "#ffffff",
        "secondary": "#facc15",
        "on-surface-variant": "#334155",
        "on-surface": "#000000",
        "secondary-container": "#fef3c7",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#fbbf24",
        "inverse-surface": "#000000",
        "on-tertiary-fixed": "#431407",
        "surface-dim": "#f1f5f9",
        "on-primary-fixed": "#7c2d12",
        "on-error": "#ffffff",
        "outline-variant": "#000000",
        "surface-bright": "#ffffff",
        "surface": "#ffffff",
        "tertiary-container": "#ffedd5",
        "tertiary-fixed-dim": "#fdba74",
        "surface-container-low": "#fffbeb",
        "primary-fixed": "#ffedd5",
        "on-tertiary-container": "#431407",
        "error": "#ef4444",
        "tertiary-fixed": "#ffedd5",
        "surface-container": "#fef3c7",
        "on-tertiary-fixed-variant": "#9a3412",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#ffedd5",
        "on-primary-fixed-variant": "#ea580c",
        "inverse-on-surface": "#fafafa",
        "primary-fixed-dim": "#fdba74",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#ffedd5",
        "error-container": "#fee2fee",
        "primary": "#f97316",
        "inverse-primary": "#fdba74",
        "surface-variant": "#f8fafc",
        "tertiary": "#ea580c",
        "secondary-fixed": "#fef3c7",
        "surface-container-highest": "#fde047",
        "on-secondary-container": "#78350f",
        "on-error-container": "#7f1d1d",
        "on-primary-container": "#7c2d12",
        "outline": "#000000",
        "background": "#fffbeb",
        "on-secondary-fixed-variant": "#b45309"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "border-width-sm": "2px",
        "border-width": "4px",
        "shadow-offset": "6px"
      }
    },
  },
  plugins: [],
}
