/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1b1b",
        "on-secondary-fixed": "#1b1735",
        "surface-tint": "#1b6b4f",
        "on-secondary": "#ffffff",
        "secondary": "#5f5a7c",
        "on-surface-variant": "#3f4943",
        "on-surface": "#1b1b1b",
        "secondary-container": "#dcd5fd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c8c2e9",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#211b00",
        "surface-dim": "#dadada",
        "on-primary-fixed": "#002115",
        "on-error": "#ffffff",
        "outline-variant": "#bec9c2",
        "surface-bright": "#f9f9f9",
        "surface": "#f9f9f9",
        "tertiary-container": "#ffe353",
        "tertiary-fixed-dim": "#e2c62d",
        "surface-container-low": "#f3f3f3",
        "primary-fixed": "#a6f2cf",
        "on-tertiary-container": "#746400",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffe24c",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed-variant": "#524600",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#a7f3d0",
        "on-primary-fixed-variant": "#00513a",
        "inverse-on-surface": "#f1f1f1",
        "primary-fixed-dim": "#8bd6b4",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "primary": "#1b6b4f",
        "inverse-primary": "#8bd6b4",
        "surface-variant": "#e2e2e2",
        "tertiary": "#6d5e00",
        "secondary-fixed": "#e5deff",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-container": "#605b7d",
        "on-error-container": "#93000a",
        "on-primary-container": "#247156",
        "outline": "#6f7973",
        "background": "#f9f9f9",
        "on-secondary-fixed-variant": "#474363"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "border-width-sm": "2px",
        "border-width": "4px",
        "shadow-offset": "6px"
      }
    },
  },
  plugins: [],
}
