/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "var(--on-background)",
        "on-secondary-fixed": "#1b1735",
        "surface-tint": "#1b6b4f",
        "on-secondary": "#ffffff",
        "secondary": "#5f5a7c",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-surface": "var(--on-surface)",
        "secondary-container": "#dcd5fd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c8c2e9",
        "inverse-surface": "var(--inverse-surface)",
        "on-tertiary-fixed": "#211b00",
        "surface-dim": "var(--surface-dim)",
        "on-primary-fixed": "#002115",
        "on-error": "#ffffff",
        "outline-variant": "var(--outline-variant)",
        "surface-bright": "var(--surface-bright)",
        "surface": "var(--surface)",
        "tertiary-container": "#ffe353",
        "tertiary-fixed-dim": "#e2c62d",
        "surface-container-low": "var(--surface-container-low)",
        "primary-fixed": "#a6f2cf",
        "on-tertiary-container": "#746400",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffe24c",
        "surface-container": "var(--surface-container)",
        "on-tertiary-fixed-variant": "#524600",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#a7f3d0",
        "on-primary-fixed-variant": "#00513a",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "primary-fixed-dim": "#8bd6b4",
        "on-tertiary": "#ffffff",
        "surface-container-high": "var(--surface-container-high)",
        "error-container": "#ffdad6",
        "primary": "#1b6b4f",
        "inverse-primary": "#8bd6b4",
        "surface-variant": "var(--surface-variant)",
        "tertiary": "#6d5e00",
        "secondary-fixed": "#e5deff",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-secondary-container": "#605b7d",
        "on-error-container": "#93000a",
        "on-primary-container": "#247156",
        "outline": "var(--outline)",
        "background": "var(--background)",
        "on-secondary-fixed-variant": "#474363"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "border-width-sm": "2px",
        "border-width": "4px",
        "shadow-offset": "6px"
      }
    },
  },
  plugins: [],
}
